name: Automated releases for npm packages.
on:
  push:
    branches:
      - master
uses: mikeal/merge-release@v4.0.7
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}